### ISSUE TITLE
run Bfloes.py

### ISSUE THREAD

**Issue by Show21** [Huangmachi/BFlows#1]
monitor: Exception occurred during handler processing. Backtrace from offending handler [_flow_stats_reply_handler] servicing event [EventOFPFlowStatsReply] follows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/nxx/ryu/ryu/app/BFlows-master/network_monitor.py", line 117, in _flow_stats_reply_handler
    for stat in sorted([flow for flow in body if (flow.priority not in [0, 65535])]):
TypeError: unorderable types: OFPFlowStats() < OFPFlowStats()

I use python3.7

**Comment by Huangmachi** [comment]
You should use Python2.
 
From: Show21
Date: 2020-11-07 16:50
To: Huangmachi/BFlows
CC: Subscribed
Subject: [Huangmachi/BFlows] run Bfloes.py (#1)
monitor: Exception occurred during handler processing. Backtrace from offending handler [_flow_stats_reply_handler] servicing event [EventOFPFlowStatsReply] follows.
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop
handler(ev)
File "/home/nxx/ryu/ryu/app/BFlows-master/network_monitor.py", line 117, in _flow_stats_reply_handler
for stat in sorted([flow for flow in body if (flow.priority not in [0, 65535])]):
TypeError: unorderable types: OFPFlowStats() < OFPFlowStats()
I use python3.7
